// const promise = new Promise((resolve, reject) => {
//     reject('oops');
// });

// promise
//     .then((data) => console.log(data))
//     .catch((err) => console.log(err));


/** Second way  */
// Promise.resolve(100).then((data) => console.log(data))


// /** with some delay */

// const promise = new Promise((resolve, reject) => {
//     setTimeout(() => (
//           resolve(1000)
//     ), 5000)
// })

// promise.then((data) => console.log(data))
// .catch((err) => console.log(err))

